import { TokenAnalysis, ScanStats } from "@/types/token";

export const mockStats: ScanStats = {
  totalScanned: 12847,
  rugsDetected: 4231,
  safeTokens: 3102,
  activeChains: 3,
};

export const mockTokens: TokenAnalysis[] = [
  {
    address: "0x1a2b3c4d5e6f7890abcdef1234567890abcdef12",
    name: "PepeFork",
    symbol: "PEPEF",
    chain: "base",
    price: 0.00000142,
    marketCap: 142000,
    liquidity: 45000,
    lpLocked: true,
    lpLockDuration: "6 months",
    honeypot: false,
    buyTax: 0,
    sellTax: 0,
    ownershipRenounced: true,
    mintable: false,
    topHolderPercent: 8.2,
    holders: 1240,
    age: "2h ago",
    riskScore: 15,
    riskLevel: "safe",
    risks: [],
    positives: ["LP locked 6 months", "Ownership renounced", "0/0 tax", "Low whale concentration"],
    createdAt: new Date().toISOString(),
  },
  {
    address: "0xdeadbeef1234567890abcdef1234567890abcdef",
    name: "ElonMoonShot",
    symbol: "ELON2",
    chain: "bsc",
    price: 0.00000003,
    marketCap: 30000,
    liquidity: 5000,
    lpLocked: false,
    honeypot: false,
    buyTax: 5,
    sellTax: 15,
    ownershipRenounced: false,
    mintable: true,
    topHolderPercent: 45.3,
    holders: 89,
    age: "15m ago",
    riskScore: 92,
    riskLevel: "critical",
    risks: [
      "LP NOT locked",
      "Ownership NOT renounced",
      "Mintable — dev can print tokens",
      "15% sell tax",
      "Top holder owns 45.3%",
      "Very low liquidity ($5k)",
      "Only 89 holders",
    ],
    positives: [],
    createdAt: new Date().toISOString(),
  },
  {
    address: "7xKXtg2CW87d97TXJSDpbD5jBkheTqA83TZRuJosgAsU",
    name: "BonkKiller",
    symbol: "BKILL",
    chain: "solana",
    price: 0.0000089,
    marketCap: 890000,
    liquidity: 120000,
    lpLocked: true,
    lpLockDuration: "30 days",
    honeypot: false,
    buyTax: 0,
    sellTax: 2,
    ownershipRenounced: false,
    mintable: false,
    topHolderPercent: 22.1,
    holders: 3400,
    age: "1d ago",
    riskScore: 45,
    riskLevel: "warning",
    risks: [
      "Ownership NOT renounced",
      "Top holder owns 22.1%",
      "LP lock only 30 days",
    ],
    positives: ["Good liquidity ($120k)", "Not mintable", "Low tax (0/2)", "3400+ holders"],
    createdAt: new Date().toISOString(),
  },
  {
    address: "0xabcdef1234567890abcdef1234567890abcdef12",
    name: "SafeDoge",
    symbol: "SDOGE",
    chain: "base",
    price: 0.0000256,
    marketCap: 2560000,
    liquidity: 380000,
    lpLocked: true,
    lpLockDuration: "1 year",
    honeypot: false,
    buyTax: 1,
    sellTax: 1,
    ownershipRenounced: true,
    mintable: false,
    topHolderPercent: 5.1,
    holders: 8900,
    age: "3d ago",
    riskScore: 8,
    riskLevel: "safe",
    risks: [],
    positives: [
      "LP locked 1 year",
      "Ownership renounced",
      "Very low tax (1/1)",
      "Strong holder base (8900+)",
      "High liquidity ($380k)",
      "Low whale concentration (5.1%)",
    ],
    createdAt: new Date().toISOString(),
  },
  {
    address: "0xfeedfacecafebeef1234567890abcdef12345678",
    name: "TrumpInu",
    symbol: "TRUMPI",
    chain: "bsc",
    price: 0.0000001,
    marketCap: 10000,
    liquidity: 2000,
    lpLocked: false,
    honeypot: true,
    buyTax: 0,
    sellTax: 99,
    ownershipRenounced: false,
    mintable: true,
    topHolderPercent: 78.5,
    holders: 23,
    age: "5m ago",
    riskScore: 99,
    riskLevel: "critical",
    risks: [
      "🚨 HONEYPOT DETECTED — cannot sell",
      "99% sell tax",
      "LP NOT locked",
      "Mintable",
      "Owner holds 78.5%",
      "Only 23 holders",
      "Micro liquidity ($2k)",
    ],
    positives: [],
    createdAt: new Date().toISOString(),
  },
];
